version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  fastapi-app:
    build:
      context: .
    container_name: fastapi_app_container
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres_data:
  ollama_data: